FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GameFrameX.FileServer/GameFrameX.FileServer.csproj", "GameFrameX.FileServer/"]
RUN dotnet restore "GameFrameX.FileServer/GameFrameX.FileServer.csproj"
COPY . .
WORKDIR "/src/GameFrameX.FileServer"
RUN dotnet build "GameFrameX.FileServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GameFrameX.FileServer.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GameFrameX.FileServer.dll"]
