FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["GameFrameX.Web.FileServer/GameFrameX.Web.FileServer.csproj", "GameFrameX.Web.FileServer/"]
RUN dotnet restore "GameFrameX.Web.FileServer/GameFrameX.Web.FileServer.csproj"
COPY . .
WORKDIR "/src/GameFrameX.Web.FileServer"
RUN dotnet build "GameFrameX.Web.FileServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GameFrameX.Web.FileServer.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GameFrameX.Web.FileServer.dll"]
